version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: teller
      POSTGRES_PASSWORD: teller_dev
      POSTGRES_DB: teller_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teller"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
