services:
  - type: web
    name: teller-codex10-9
    runtime: python
    pythonVersion: "3.12"
    plan: starter
    region: oregon
    buildCommand: pip install -r python/requirements.txt
    startCommand: 'python python/teller.py '
    healthCheckPath: /api/healthz
    autoDeploy: true
    repo: https://github.com/dvanosdol88/teller-codex10-9
