services:
  - type: web
    name: teller-codex10-9
    runtime: python
    plan: starter
    region: oregon
    buildCommand: pip install -r python/requirements.txt
    startCommand: 'python python/teller.py '
    healthCheckPath: /api/healthz
    autoDeploy: true
    repo: https://github.com/dvanosdol88/teller-codex10-9
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: TELLER_APPLICATION_ID
        value: "YOUR_TELLER_APPLICATION_ID"